### ISSUE TITLE
Wrong center calculation

### ISSUE THREAD

**Issue by wernerolaf** [rbaltrusch/pygame_examples#4]
In hexagon.py file center is being calculated in wrong manner as x position also needs adjustment below is corrected code 
 
@property
def centre(self) -> Tuple[float, float]:
    """Centre of the hexagon"""
    x, y = self.position  # pylint: disable=invalid-name
    return (x + self.radius / 2 , y + self.minimal_radius)

**Comment by rbaltrusch** [comment]
## Before:
![before](https://user-images.githubusercontent.com/41642326/213876991-a5937d26-fb75-4168-84dd-13a3eeaf4bfb.PNG)

## After:
![after](https://user-images.githubusercontent.com/41642326/213876990-8c620eb6-9ec7-4ca0-bf5f-1a6a9959a9d4.PNG)

Thanks for submitting the issue! Fixed in commit 03633df93.
